### ISSUE TITLE
RunAsProcesses() Returns 0 for Some Errors

### ISSUE THREAD

**Issue by JoshuaJB** [yalue/hip_plugin_framework#1]
`RunAsProcesses()` in `runner.c` uses `EXIT_FAILURE` ([the value 1](https://www.gnu.org/software/libc/manual/html_node/Exit-Status.html)) to indicate failure from lines 904 through 930. The unmodified version of `all_ok` is returned on success as well. `all_ok` is 1 by default, meaning that your program will return 1 on error or on success.

😮

**Comment by yalue** [comment]
Good catch, but that's intended behavior.  The check on line 920 ensures that the `EXIT_FAILURE` or `EXIT_SUCCESS` codes only occur in a child process, where it would be incorrect to return from `RunAsProcesses`.  I did, however, adjust the comments to clarify this.
